const fieldLabels: Record<string, string> = {
  'Brand Essence': 'Essência da marca',
  Purpose: 'Propósito',
  Mission: 'Missão',
  Vision: 'Visão',
  Values: 'Valores',
  'Brand Promise': 'Promessa da marca',
  Positioning: 'Posicionamento',
  'Value Proposition': 'Proposta de valor',
  Differentiators: 'Diferenciais',
  Audience: 'Público',
  Personas: 'Personas',
  Needs: 'Necessidades',
  'Pain Points': 'Pontos de dor',
  'Brand Story': 'História da marca',
  Manifesto: 'Manifesto',
  Ambition: 'Ambição',
  'Brand Beliefs': 'Crenças da marca',
  'Brand Principles': 'Princípios da marca',
  'Reasons to Believe': 'Razões para acreditar',
  'Brand Pillars': 'Pilares da marca',
  'Brand Architecture': 'Arquitetura de marca',
  'Naming System': 'Sistema de nomes',
  'Brand Measurement': 'Medição da marca',
  'Sport lifestyle': 'Estilo de vida esportivo',
  Stakeholders: 'Públicos envolvidos',
  'Jobs to be Done': 'Tarefas a realizar',
  'Research & Evidence': 'Pesquisa e evidências',
  Voice: 'Voz',
  Tone: 'Tom',
  'Tone of Voice': 'Tom de voz',
  'Voice Principles': 'Princípios de voz',
  'Messaging Principles': 'Princípios de mensagem',
  'Brand Vocabulary': 'Vocabulário da marca',
  'Preferred Words': 'Palavras preferidas',
  'Forbidden Words': 'Palavras proibidas',
  Expressions: 'Expressões',
  Grammar: 'Gramática',
  Punctuation: 'Pontuação',
  Capitalization: 'Uso de maiúsculas',
  'English usage': 'Uso de inglês',
  'Technical language': 'Linguagem técnica',
  Humor: 'Humor',
  'Calls to action': 'Chamadas para ação',
  Headlines: 'Títulos de destaque',
  Microcopy: 'Microtexto',
  'UX Writing': 'Redação de experiência',
  'Social Media': 'Redes sociais',
  Advertising: 'Publicidade',
  'Institutional Communication': 'Comunicação institucional',
  'Customer Support': 'Atendimento ao cliente',
  'Big Idea': 'Grande ideia',
  Tagline: 'Assinatura verbal',
  'Elevator Pitch': 'Apresentação curta',
  'One-line description': 'Descrição em uma linha',
  '25-word description': 'Descrição em 25 palavras',
  '50-word description': 'Descrição em 50 palavras',
  'Institutional description': 'Descrição institucional',
  'About text': 'Texto sobre a marca',
  Boilerplate: 'Texto institucional padrão',
  'Social bio': 'Biografia para redes sociais',
  'Sales message': 'Mensagem de vendas',
  'Campaign message': 'Mensagem de campanha',
  'Product message': 'Mensagem de produto',
  'CTA library': 'Biblioteca de chamadas para ação',
  'Primary Logo': 'Logo principal',
  'Secondary Logo': 'Logo secundário',
  Symbol: 'Símbolo',
  Wordmark: 'Assinatura tipográfica',
  'Logo variations': 'Variações do logo',
  Positive: 'Versão positiva',
  Negative: 'Versão negativa',
  Monochrome: 'Versão monocromática',
  'Clear Space': 'Área de proteção',
  'Minimum Size': 'Tamanho mínimo',
  'Background Usage': 'Uso sobre fundos',
  'Incorrect Usage': 'Uso incorreto',
  'Co-branding': 'Coassinatura',
  'Logo Decision Tree': 'Árvore de decisão do logo',
  'Brand Colors': 'Cores da marca',
  'Primary Colors': 'Cores primárias',
  'Secondary Colors': 'Cores secundárias',
  'Neutral Colors': 'Cores neutras',
  'Supporting Colors': 'Cores de apoio',
  'Primary Brand Typeface': '1797',
  'Secondary Typeface': 'Tipografia secundária',
  'Display Typeface': '1797 · Poster',
  'Supporting Typeface': '1797 · Medium',
  Subjects: 'Assuntos',
  People: 'Pessoas',
  Environment: 'Ambiente',
  Lighting: 'Iluminação',
  Composition: 'Composição',
  Framing: 'Enquadramento',
  'Camera angle': 'Ângulo de câmera',
  Depth: 'Profundidade',
  Emotion: 'Emoção',
  'Color treatment': 'Tratamento de cor',
  Texture: 'Textura',
  Authenticity: 'Autenticidade',
  Scenarios: 'Cenários',
  'This is us': 'Isto é ONCI',
  "This isn't us": 'Isto não é ONCI',
  Stroke: 'Traço',
  'Corner style': 'Estilo dos cantos',
  'Filled vs outline': 'Preenchido ou contorno',
  'Optical balance': 'Equilíbrio óptico',
  Shapes: 'Formas',
  Patterns: 'Padrões',
  Frames: 'Molduras',
  Lines: 'Linhas',
  Textures: 'Texturas',
  Gradients: 'Gradientes',
  Masks: 'Máscaras',
  Containers: 'Contêineres',
  'Graphic devices': 'Recursos gráficos',
  'Decorative elements': 'Elementos decorativos',
  'Brand signatures': 'Assinaturas da marca',
  Whitespace: 'Espaço em branco',
  'Landing pages': 'Páginas de destino',
  'Logo animation': 'Animação do logo',
  'Brand reveals': 'Revelações da marca',
  Storytelling: 'Narrativa',
  Calm: 'Calmo',
  Energetic: 'Energético',
  Precise: 'Preciso',
  Playful: 'Lúdico',
  Elegant: 'Elegante',
  Expressive: 'Expressivo',
  "Do / Don't": 'Fazer / Não fazer',
  'Sonic logo': 'Logo sonoro',
  'Sound signature': 'Assinatura sonora',
  'Music direction': 'Direção musical',
  'Notification personality': 'Personalidade das notificações',
  'Podcast identity': 'Identidade de podcast',
  'Audiovisual direction': 'Direção audiovisual',
  Website: 'Site',
  Presentation: 'Apresentações',
  Email: 'E-mail',
  Print: 'Impresso',
  Packaging: 'Embalagem',
  Events: 'Eventos',
  'Customer Service': 'Atendimento ao cliente',
  Sales: 'Vendas',
  Partnerships: 'Parcerias',
  'Brand System Prompt': 'Prompt do sistema de marca',
  'Writing Prompt': 'Prompt de escrita',
  'Tone Prompt': 'Prompt de tom',
  'Image Generation Prompt': 'Prompt de geração de imagem',
  'Photography Prompt': 'Prompt de fotografia',
  'Campaign Prompt': 'Prompt de campanha',
  'Social Prompt': 'Prompt para redes sociais',
  'Forbidden Styles': 'Estilos proibidos',
  'Forbidden Language': 'Linguagem proibida',
  'Negative Prompts': 'Prompts negativos',
  Examples: 'Exemplos',
  'Evaluation Checklist': 'Lista de avaliação',
  'Brand Owner': 'Responsável pela marca',
  'Design Owner': 'Responsável pelo design',
  'Marketing Owner': 'Responsável pelo marketing',
  'Approval Process': 'Processo de aprovação',
  'Brand Version': 'Versão da marca',
  'Last Update': 'Última atualização',
  Changelog: 'Histórico de alterações',
  Stable: 'Estável',
  Beta: 'Em teste',
  Experimental: 'Experimental',
  Deprecated: 'Descontinuado',
  Assets: 'Ativos',
  'Official Files': 'Arquivos oficiais',
  'Naming Convention': 'Convenção de nomes',
  Versioning: 'Versionamento',
  Localization: 'Localização',
  'Legal & Licensing': 'Jurídico e licenciamento',
};

const moduleLabels: Record<string, string> = {
  core: 'Núcleo da marca',
  strategy: 'Estratégia de marca',
  audience: 'Públicos',
  personality: 'Personalidade da marca',
  'verbal-identity': 'Identidade verbal',
  messaging: 'Sistema de mensagens',
  storytelling: 'Narrativa da marca',
  'visual-brand-identity': 'Identidade visual da marca',
  typography: 'Tipografia',
  photography: 'Direção fotográfica',
  illustration: 'Ilustração',
  iconography: 'Iconografia',
  'graphic-language': 'Linguagem gráfica',
  layout: 'Princípios de composição',
  motion: 'Identidade de movimento',
  sonic: 'Identidade sonora',
  'brand-experience': 'Experiência da marca',
  'brand-in-action': 'Marca em ação',
  'ai-guidelines': 'Diretrizes de IA para a marca',
  governance: 'Governança da marca',
};

const groupLabels: Record<string, string> = {
  Foundation: 'Fundamentos',
  'Language & Narrative': 'Linguagem e Narrativa',
  'Visual Identity': 'Identidade Visual',
  Experience: 'Experiência',
  'AI & Governance': 'IA e Governança',
};

export const campoEmPortugues = (name: string) => fieldLabels[name] ?? name;
export const moduloEmPortugues = (id: string, fallback: string) => moduleLabels[id] ?? fallback;
export const grupoEmPortugues = (group: string) => groupLabels[group] ?? group;

export const textoEmPortugues = (value: string) => value
  .replaceAll('Brand Book', 'Manual da Marca')
  .replaceAll('Design System', 'Sistema de Design')
  .replaceAll('masterbrand', 'marca-mãe')
  .replaceAll('claims', 'alegações')
  .replaceAll('claim', 'alegação')
  .replaceAll('headlines', 'títulos de destaque')
  .replaceAll('CTAs', 'chamadas para ação')
  .replaceAll('CTA', 'chamada para ação')
  .replaceAll('stock genérico', 'banco de imagens genérico')
  .replaceAll('Fitness genérico', 'Imagem esportiva genérica')
  .replaceAll('Website', 'Site')
  .replaceAll('Events', 'Eventos')
  .replaceAll('Partnerships', 'Parcerias');
